title: Miri Liu
url: "https://emmatliu.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Personal"
   link: "personal"
 - name: "CV"
   link: "CV.pdf"
 - name: "Contact"
   link: "contact"
